services:
  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - ./api-server/.env
    volumes:
      - ./api-server/src:/app/src
    depends_on:
      - database
  database:
    image: mysql:8.0
    ports:
      - 3306:3306
    env_file:
      - ./api-server/.env
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_DATABASE: 'skintorch'